### ISSUE TITLE
Constraints for sum and relations of the variables

### ISSUE THREAD

**Issue by razvanpaul** [JWally/jsLPSolver#59]
Hello! Firstly, thank you for the library, it's just amazing.

I'm somehow new to Javascript and of course to `jsLPSolver` and I have to solve the following equation:

```
    Objective: Maximize r17
    
    Variables:
    - Floats: q7, q8, q9, q10, q11, q12, q13, q14, q15, q16, q17
    - Floats: r7, r8, r9, r10, r11, r12, r13, r14, r16, r16, r17

    Relations:
    - q7 +q8 +q9 +q10 + q11 + q12 + q13 + q14 + q15 + q16 = q17
    - r7 +r8 +r9 +r10 + r11 + r12 + r13 + r14 + r15 + r16 = r17
    - r7 = q7 / 0.50
    - r8 = q8 / 0.75
    - r9 = q9 / 0.88
    - r10 = q10 / 1.00
    - r11 = q11 / 1.13
    - r12 = q12 / 1.18
    - r13 = q13 / 1.76
    - r14 = q14 / 2.11
    - r15 = q15 / 2.33
    - r16 = q16 / 2.50

    Constraints:
    - 1000 <= q7 <= 17500
    - 2000 <= q8 <= 6300
    - 5000 <= q9 <= 19292
    - 1200 <= q10 <= 29820
    - 100 <= q11 <=2887.50
    - 700 <= q12 <= 20825
    - 300 <= q13 <= 9481.50
    - 150 <= q14 <= 5764.50,
    - 1200 <= q15 <= 48594,
    - 300 <= q16 <= 12600 
    - 60500 <= q17 <= 60500
```

Basically, I don't have any idea right now how could I plug in these rules into the library's `model`. Like the relations or the sum constraints?
